# Import Libraries

In [1]:
import os
os.getcwd()

'E:\\PYTHONCLASSJUPYTER\\PrakashSenapati\\2024_10_23_Xgboost'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

# Load & Preview Dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.shape

(10000, 14)

In [6]:
dataset.head()

apst  CustomerId   Surname  CreditScore  Geography  Gender  Age  Tenure  \
0     1    15634602  Hargrave          619      delhi  Female   42       2   
1     2    15647311      Hill          608  bangalore  Female   41       1   
2     3    15619304      Onio          502      delhi  Female   42       8   
3     4    15701354      Boni          699      delhi  Female   39       1   
4     5    15737888  Mitchell          850  bangalore  Female   43       2   

     Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0       0.00              1          1               1        101348.88   
1   83807.86              1          0               1        112542.58   
2  159660.80              3          1               0        113931.57   
3       0.00              2          0               0         93826.63   
4  125510.82              1          1               1         79084.10   

   Exited  
0       1  
1       0  
2       1  
3       0  
4       0

# Splitting into Independent (X) and Dependent (y) variable

In [14]:
# Independent variables or columns or dataset

dataset.columns[3:13]

Index(['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance',
       'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary'],
      dtype='object')

In [16]:
# Dependent variable or column or dataset

dataset.columns[-1]

'Exited'

In [130]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [9]:
print(X.shape)
print(y.shape)

(10000, 10)
(10000,)


In [12]:
print( X[0:10] )

[[619 'delhi' 'Female' 42 2 0.0 1 1 1 101348.88]
 [608 'bangalore' 'Female' 41 1 83807.86 1 0 1 112542.58]
 [502 'delhi' 'Female' 42 8 159660.8 3 1 0 113931.57]
 [699 'delhi' 'Female' 39 1 0.0 2 0 0 93826.63]
 [850 'bangalore' 'Female' 43 2 125510.82 1 1 1 79084.1]
 [645 'bangalore' 'Male' 44 8 113755.78 2 1 0 149756.71]
 [822 'delhi' 'Male' 50 7 0.0 2 1 1 10062.8]
 [376 'mumbai' 'Female' 29 4 115046.74 4 1 0 119346.88]
 [501 'delhi' 'Male' 44 4 142051.07 2 0 1 74940.5]
 [684 'delhi' 'Male' 27 2 134603.88 1 1 1 71725.73]]


In [15]:
print( y[0:10] )

[1 0 1 0 0 1 0 1 0 0]


# Label Encoding the `Gender` column

In [132]:
X.shape

(10000, 10)

In [131]:
print( np.array(np.unique(X[:, 2], return_counts=True)).T )

[['Female' 4543]
 ['Male' 5457]]


In [133]:
X[:, 2][0:10]

array(['Female', 'Female', 'Female', 'Female', 'Female', 'Male', 'Male',
       'Female', 'Male', 'Male'], dtype=object)

In [134]:
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [135]:
X.shape

(10000, 10)

In [137]:
X[:, 2][0:10]

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1], dtype=object)

In [138]:
print( X[0:10] )

[[619 'delhi' 0 42 2 0.0 1 1 1 101348.88]
 [608 'bangalore' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'delhi' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'delhi' 0 39 1 0.0 2 0 0 93826.63]
 [850 'bangalore' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'bangalore' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'delhi' 1 50 7 0.0 2 1 1 10062.8]
 [376 'mumbai' 0 29 4 115046.74 4 1 0 119346.88]
 [501 'delhi' 1 44 4 142051.07 2 0 1 74940.5]
 [684 'delhi' 1 27 2 134603.88 1 1 1 71725.73]]


# One Hot Encoding the `Geography` Column

In [139]:
X.shape

(10000, 10)

In [143]:
print( np.array(np.unique(X[:, 1], return_counts=True)).T )

[['bangalore' 2477]
 ['delhi' 5014]
 ['mumbai' 2509]]


In [144]:
X[:, 1][0:10]

array(['delhi', 'bangalore', 'delhi', 'delhi', 'bangalore', 'bangalore',
       'delhi', 'mumbai', 'delhi', 'delhi'], dtype=object)

In [145]:
print( X[0:10] )

[[619 'delhi' 0 42 2 0.0 1 1 1 101348.88]
 [608 'bangalore' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'delhi' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'delhi' 0 39 1 0.0 2 0 0 93826.63]
 [850 'bangalore' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'bangalore' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'delhi' 1 50 7 0.0 2 1 1 10062.8]
 [376 'mumbai' 0 29 4 115046.74 4 1 0 119346.88]
 [501 'delhi' 1 44 4 142051.07 2 0 1 74940.5]
 [684 'delhi' 1 27 2 134603.88 1 1 1 71725.73]]


In [146]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [147]:
X.shape

(10000, 12)

In [148]:
print( X[0:10] )

[[0.0 1.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [1.0 0.0 0.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [0.0 1.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [0.0 1.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]
 [1.0 0.0 0.0 850 0 43 2 125510.82 1 1 1 79084.1]
 [1.0 0.0 0.0 645 1 44 8 113755.78 2 1 0 149756.71]
 [0.0 1.0 0.0 822 1 50 7 0.0 2 1 1 10062.8]
 [0.0 0.0 1.0 376 0 29 4 115046.74 4 1 0 119346.88]
 [0.0 1.0 0.0 501 1 44 4 142051.07 2 0 1 74940.5]
 [0.0 1.0 0.0 684 1 27 2 134603.88 1 1 1 71725.73]]


In [150]:
# 'bangalore'

print( np.array(np.unique(X[:, 0], return_counts=True)).T )

[[0.0 7523]
 [1.0 2477]]


In [151]:
# 'delhi'

print( np.array(np.unique(X[:, 1], return_counts=True)).T )

[[0.0 4986]
 [1.0 5014]]


In [152]:
# 'mumbai'

print( np.array(np.unique(X[:, 2], return_counts=True)).T )

[[0.0 7491]
 [1.0 2509]]


# Splitting the dataset into the Training set and Testing set

In [153]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [154]:
print( X_train.shape)
print( X_test.shape)
print( y_train.shape)
print( y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


In [155]:
print( X_train[0:5] )

[[1.0 0.0 0.0 667 0 34 5 0.0 2 1 0 163830.64]
 [0.0 0.0 1.0 427 1 42 1 75681.52 1 1 1 57098.0]
 [0.0 1.0 0.0 535 0 29 2 112367.34 1 1 0 185630.76]
 [1.0 0.0 0.0 654 1 40 5 105683.63 1 1 0 173617.09]
 [1.0 0.0 0.0 850 0 57 8 126776.3 2 1 1 132298.49]]


In [156]:
print( X_test[0:5] )

[[0.0 0.0 1.0 597 0 35 8 131101.04 1 1 1 192852.67]
 [0.0 1.0 0.0 523 0 40 2 102967.41 1 1 0 128702.1]
 [1.0 0.0 0.0 706 0 42 8 95386.82 1 1 1 75732.25]
 [0.0 1.0 0.0 788 1 32 4 112079.58 1 0 0 89368.59]
 [0.0 0.0 1.0 706 1 38 5 163034.82 2 1 1 135662.17]]


In [157]:
print( y_train[0:5] )

[0 0 0 0 0]


In [158]:
print( y_test[0:5] )

[0 1 0 0 0]


# Training XGBoost Classifier

In [159]:
xgb_classifier = XGBClassifier()
xgb_classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [160]:
y_pred = xgb_classifier.predict(X_test)

In [161]:
y_pred.shape

(2000,)

In [162]:
print( y_pred[0:20] )

[1 0 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0]


In [163]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1492  103]
 [ 192  213]]


In [164]:
ac = accuracy_score(y_test, y_pred)
print(ac)

0.8525


In [165]:
bias = xgb_classifier.score(X_train, y_train)
bias

0.957625

**_Applying k-Fold Cross Validation_**

In [166]:
accuracies = cross_val_score(estimator=xgb_classifier, X=X_train, y=y_train, cv=10)

print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 85.20 %
Standard Deviation: 1.23 %
